# bunfig.toml
[test]
preload = ["./src/test/@pretest.ts"]
timeout = 30000                                                            # 30 seconds
coverageReporter = ["text", "lcov"]
coveragePathIgnorePatterns = ["dist/**", "node_modules/**", "src/test/**"]

[install]
optional = true
dev = true
peer = true
