import { ScalarPlugin } from '../plugins/scalar';
import { Shokupan } from '../shokupan';

// Import the statically analyzed spec (generated by `shokupan analyze`)
import staticSpec from './openapi.json';

const app = new Shokupan({
    port: 3001,
    development: true,
});

// Demonstrates automatic type detection from type conversions
app.get('/users', {
    summary: 'Bloop',
    description: 'Potstedasd'
}, (ctx) => {
    const role = ctx.query.role;                    // string (default)
    const page = parseInt(ctx.query.page);          // integer ← Detected!
    const limit = parseInt(ctx.query.limit);        // integer ← Detected!
    const active = Boolean(ctx.query.active);       // boolean ← Detected!

    return ctx.json({
        users: [],
        filters: { role, page, limit, active }
    });
});

app.post('/users', async (ctx) => {
    const body = await ctx.body();                  // request body ← Detected!
    return ctx.json({
        created: true,
        user: body
    });
});

app.post('/users/data', async (ctx) => {
    const body = await ctx.body() as { name: string; age: number; };                  // request body ← Detected!
    return ctx.json({
        created: true,
        user: body
    });
});

app.get('/users/:id', (ctx) => {
    const id = parseInt(ctx.params.id);             // integer path param ← Detected!
    return ctx.json({
        user: { id, name: 'John Doe' }
    });
});

app.get('/products', (ctx) => {
    const category = ctx.query.category;            // string
    const minPrice = parseFloat(ctx.query.minPrice); // float ← Detected!
    const maxPrice = parseFloat(ctx.query.maxPrice); // float ← Detected!
    const inStock = !!ctx.query.inStock;            // boolean ← Detected!

    return ctx.json({
        products: [],
        filters: { category, minPrice, maxPrice, inStock }
    });
});

// Route with explicit spec that gets enhanced by runtime analysis
app.get('/search',
    {
        summary: 'Search items',
        description: 'Search for items by query string with pagination',
        tags: ['Search']
    },
    (ctx) => {
        const q = ctx.query.q;                       // string
        const filter = ctx.query.filter;             // string
        const page = parseInt(ctx.query.page);       // integer ← Auto-added!
        const limit = parseInt(ctx.query.limit);     // integer ← Auto-added!

        return ctx.json({
            results: [],
            query: { q, filter, page, limit }
        });
    }
);

// Response format detection examples
app.get('/page/:slug', (ctx) => {
    const slug = ctx.params['slug'];
    return ctx.html(`<html><body><h1>${slug}</h1></body></html>`);
});

app.get('/info', (ctx) => {
    return ctx.text('This is plain text information');
});

app.get('/download/:filename', (ctx) => {
    const filename = ctx.params['filename'];
    return ctx.file(`/files/${filename}`);
});

app.get('/redirect-example', (ctx) => {
    return ctx.redirect('/users');
});

// Error handling with status codes
app.post('/users/:id/update', async (ctx) => {
    const id = parseInt(ctx.params['id']);
    const body = await ctx.body();

    if (!body) {
        return ctx.json({ error: 'Request body required' }, 400);
    }

    if (id < 0) {
        return ctx.json({ error: 'Invalid ID' }, 422);
    }

    return ctx.json({ updated: true, user: { id, ...body } });
});


// Mount enhanced Scalar viewer
app.mount('/scalar', new ScalarPlugin({
    enableStaticAnalysis: true,
    baseDocument: {
        ...(staticSpec as any),
        info: {
            title: 'Shokupan Open API',
            version: '1.0.0',
            description: 'API documentation for Shokupan',
        },
        servers: [{
            url: 'http://localhost:3001',
            description: 'Local Development'
        }]
    },
    config: {}
}));

console.log(`
🚀 Demo server with runtime type & response detection running...
📖 Visit http://localhost:3002/docs to see the OpenAPI spec

✨ Parameters are automatically typed:
   • parseInt() → integer
   • parseFloat() → number (float)
   • Boolean() or !! → boolean
   • default → string

✨ Responses are automatically detected:
   • ctx.json() → application/json
   • ctx.html() → text/html
   • ctx.text() → text/plain
   • ctx.file() → binary file
   • ctx.redirect() → 302 redirect
   • return { } → application/json (fallback)
`);

app.listen();
