name: Benchmark
on: 
  workflow_dispatch: # Allows you to start it manually
  push:
    tags:
      - 'v*'
jobs:
  benchmark:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions: 
      contents: write
    
    steps:
      - uses: actions/checkout@v6

      - name: Configure Git User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - name: Install Main Dependencies
        run: bun install
      - name: Install Bench Dependencies
        working-directory: benchmarking
        run: bun install
    
      - name: Run Basic benchmark
        run: bun run bench --all

      - name: Run Advanced benchmark
        run: bun run bench:advanced --all

      - run: mkdir -p /tmp/reports
      - run: cp src/benchmarking/*.html /tmp/reports/
      
      - name: Upload to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /tmp/reports
          keep_files: true