name: Documentation

on:
  # Runs on pushes to main branch
  push:
    branches: [dev]
    paths:
      - 'docs/**'
      - '.github/workflows/deploy-docs.yml'
  
  # Allows manual trigger from Actions tab
  workflow_dispatch:

# Sets permissions for GitHub Pages deployment
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies 1
        run: bun install

      - name: Install dependencies 2
        working-directory: ./docs
        run: bun install

      - name: Build documentation
        working-directory: ./docs
        run: bun run build

      - run: cp benchmarking/report.html docs/dist/report.html
      - run: cp benchmarking/advanced-report.html docs/dist/advanced-report.html

      - name: Upload to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/dist
          keep_files: true

